// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSsS6fcbnTXQki5QFur5E_5831K9MKltQ',
    appId: '1:9807549374:web:e57b5352cee92f42961fef',
    messagingSenderId: '9807549374',
    projectId: 'flutter-cloud-firestore-f68b1',
    authDomain: 'flutter-cloud-firestore-f68b1.firebaseapp.com',
    databaseURL: 'https://flutter-cloud-firestore-f68b1-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-cloud-firestore-f68b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLXXPieSbLKX1DCllAeEwbLP2xZPzSMwE',
    appId: '1:9807549374:android:f30465e5f54d1f0e961fef',
    messagingSenderId: '9807549374',
    projectId: 'flutter-cloud-firestore-f68b1',
    databaseURL: 'https://flutter-cloud-firestore-f68b1-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-cloud-firestore-f68b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeSEfAgLjDVB3N7pNy1CtrjGjo2cqG5CM',
    appId: '1:9807549374:ios:987e72b3b6860b24961fef',
    messagingSenderId: '9807549374',
    projectId: 'flutter-cloud-firestore-f68b1',
    databaseURL: 'https://flutter-cloud-firestore-f68b1-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-cloud-firestore-f68b1.appspot.com',
    iosClientId: '9807549374-6vmt30hnsqj8t5hq01lparqjevbl9oad.apps.googleusercontent.com',
    iosBundleId: 'com.example.desafioModulo4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeSEfAgLjDVB3N7pNy1CtrjGjo2cqG5CM',
    appId: '1:9807549374:ios:987e72b3b6860b24961fef',
    messagingSenderId: '9807549374',
    projectId: 'flutter-cloud-firestore-f68b1',
    databaseURL: 'https://flutter-cloud-firestore-f68b1-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-cloud-firestore-f68b1.appspot.com',
    iosClientId: '9807549374-6vmt30hnsqj8t5hq01lparqjevbl9oad.apps.googleusercontent.com',
    iosBundleId: 'com.example.desafioModulo4',
  );
}
